# Site settings
title: "Dr Luca Kozma"
image: "3.jpeg"
links:
  - label: ORCiD
    url: "https://orcid.org/0000-0002-3297-629X"
  - label: Email
    url: "mailto:luca.kozma@uws.ac.uk"
  - label: LinkedIn
    url: "https://www.linkedin.com/in/dr-luca-kozma-phd-079432135/"
  - label: Twitter
    url: "https://twitter.com/lucakozma"
site: bookdown::bookdown_site
output:
  postcards::trestles
knit: rmarkdown::render

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Luca Kozma"
resume_title:                   "Lecturer at the University of West of Scotland"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "luca.kozma@uws.ac.uk"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_twitter_url:           "http://twitter.com/lucakozma"
  resume_ORCId_url:          "https://orcid.org/0000-0002-3297-629X"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/dr-luca-kozma-phd-079432135/"
  # resume_instagram_url:         "insert your Instagram URL here"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
